workspace:
  base: /go
  path: src/github.sakura.codes/m-yamamoto/drone-test

pipeline:
  test:
    image: golang:1.6
    commands:
      - go test
  command:
    image: busybox
    commands:
      - echo $SLACK_WEBHOOK
  slack:
    image: plugins/slack
    channel: times_m-yamamoto
    username: drone
