workspace:
  base: /go
  path: src/github.sakura.codes/m-yamamoto/drone-test

pipeline:
  test:
    image: golang:1.6
    commands:
      - go test
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
