workspace:
  base: /go
  path: src/github.sakura.codes/m-yamamoto/drone-test

pipeline:
  test:
    image: golang:1.6
    commands:
      - go test
  slack:
    image: plugins/slack
    webhook: webhook: https://hooks.slack.com/services
    channel: times_m-yamamoto
    username: drone
